---
  - name: Install RDS Server Role
    win_feature:
      name: "RDS-RD-SERVER"
      state: "{{ win_feature_rds_server_state }}"
    notify: Reboot Machine

  - name: Flush Handlers
    meta: flush_handlers
