---
  - name: Install RDS Server Role
    win_feature:
      name: "RDS-RD-SERVER"
      state: "{{ win_feature_rds_server_state }}"
    register: win_feature
  - name: Reboot the machine
    win_reboot:
      pre_reboot_delay: 10
    when: win_feature.reboot_required
